package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-07-14T17:11:46.812-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "Titulos", 
                  wsdlLocation = "file:/C:/Users/michel.barbosa/AnypointStudio/workspace/trabalho-final/wsdl/Titulos.wsdl",
                  targetNamespace = "http://www.example.org/Titulos/") 
public class Titulos_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/Titulos/", "Titulos");
    public final static QName TitulosSOAP = new QName("http://www.example.org/Titulos/", "TitulosSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/michel.barbosa/AnypointStudio/workspace/trabalho-final/wsdl/Titulos.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Titulos_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/michel.barbosa/AnypointStudio/workspace/trabalho-final/wsdl/Titulos.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Titulos_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Titulos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Titulos_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Titulos_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Titulos_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Titulos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Titulos
     */
    @WebEndpoint(name = "TitulosSOAP")
    public Titulos getTitulosSOAP() {
        return super.getPort(TitulosSOAP, Titulos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Titulos
     */
    @WebEndpoint(name = "TitulosSOAP")
    public Titulos getTitulosSOAP(WebServiceFeature... features) {
        return super.getPort(TitulosSOAP, Titulos.class, features);
    }

}
