
package wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-07-14T17:11:46.754-03:00
 * Generated source version: 2.5.1
 * 
 */
public final class Titulos_TitulosSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/Titulos/", "Titulos");

    private Titulos_TitulosSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Titulos_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Titulos_Service ss = new Titulos_Service(wsdlURL, SERVICE_NAME);
        Titulos port = ss.getTitulosSOAP();  
        
        {
        System.out.println("Invoking buscaTitulos...");
        wsdl.Busca _buscaTitulos_parameters = null;
        wsdl.Titulos_Type _buscaTitulos__return = port.buscaTitulos(_buscaTitulos_parameters);
        System.out.println("buscaTitulos.result=" + _buscaTitulos__return);


        }

        System.exit(0);
    }

}
